services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_psql
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/app
    ports:
      - "8085:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase

  db:
    image: nickblah/postgis
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    container_name: psql_db
    ports:
      - "5432:5432"
    volumes:
      - ./psql_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  psql_data:
