# Generated by Django 4.2.15 on 2024-08-08 10:48

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('location_polygon', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('location_point', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(69.2401, 41.2995), srid=4326)),
            ],
        ),
    ]
